"use client";
import { Suspense } from "react";
import { I18nextProvider } from "react-i18next";
import { Geist, Geist_Mono } from "next/font/google";
import { useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import "./globals.css";
import './i18n'; // Importa la configuración de i18next

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { i18n } = useTranslation();
  useEffect(() => {
    const lng = i18n.language || 'en';
    document.documentElement.lang = lng;
  }, [i18n.language]);
  return (
    <I18nextProvider i18n={i18n}>
    <html lang="en" class="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
    </I18nextProvider>
  );
}
